<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="true" />
<meta name="allow-skip" content="true" />

<title>Inference for Simple Linear Regression</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-learning-outcomes" class="section level2">
<h2>Learning Outcomes</h2>
<p>Our goal in this module will be to obtain the tools we need to be able to do <em>inference</em> on the simple linear regression model. That is, we want to generate confidence intervals for the slope and intercept parameters (<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>), and also carry out hypothesis tests of statments about those parameters.</p>
<p>To achieve this goal, we’ll consider two <em>more</em> ways of estimating the <span class="math inline">\(\beta\)</span>s (<em>you didn’t think there could be even</em> <strong>more</strong>, <em>did you?</em>) and then, more crucially, determine the sampling distributions for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. (Once we know the sampling distributions, the machinery to find CIs and do tests will follow.)</p>
<p>By the end of the module you will:</p>
<ol style="list-style-type: decimal">
<li>Know it’s possible to find the least-squares estimates for the parameters <span class="math inline">\(beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> using geometry and vector algebra</li>
<li>Understand the derivation of these same parameter estimates using linear algebra, including the definition of the “hat” matrix <span class="math inline">\(\mathbf{H}\)</span> that satisfies <span class="math inline">\(\mathbf{H}\mathbf{y} = \hat{\mathbf{y}}\)</span></li>
<li>Derive the sampling distribution of the slope parameter <span class="math inline">\(\beta_1\)</span>, finding that <span class="math inline">\(B_1 \sim N(\beta_1, \frac{\sigma}{\mid \mathbf{x} - \mathbf{\bar{x}}\mid})\)</span></li>
<li>Derive the sampling distribution of the intercept parameter <span class="math inline">\(\beta_0\)</span>, finding that <span class="math inline">\(B_0 \sim N(\beta_0, \sigma \sqrt{\frac{1}{n} + \frac{\bar{\mathbf{x}}^2}{S_{xx}}})\)</span></li>
<li>Find an unbiased estimator for the residual variance, <span class="math inline">\(\hat{\sigma^2} = \frac{1}{(n-2)} \sum_{i=1}^{n} e_i^2\)</span></li>
<li>Use the findings above to obtain a method to construct confidence intervals and do hypothesis tests about the <span class="math inline">\(\beta\)</span>s (<em>Yesssss! This is regression inference. Objective met.</em>)</li>
</ol>
<p><em>These materials come from your text book, FAStR2 Chapter 6.3.4 - 6.4.5.</em></p>
</div>
<div id="section-bases-orthogonality-projectionsoh-my" class="section level2">
<h2>Bases, Orthogonality, Projections…Oh, My!</h2>
<p>Are orthogonal and orthonormal bases and projections the stuff of your dreams, or confusing nightmares?</p>
<p><em>If you love them, by all means</em> <strong>please read 6.3.4</strong> <em>in your text book, which illustrates how to derive least squares parameter estimates via geometry and vector algebra.</em></p>
<p><em>If not, it’s OK. Take a peek just to see how you feel about it and if needed, carefully proceed around that section and don’t worry about it.</em></p>
<p>This section is lovely and quite possibly also confusing. The amount you <em>already know</em> about geometry and vector algebra probably determines which (there are potentially lots of concepts and notation that are not familiar). So, we will focus on other approaches.</p>
</div>
<div id="section-regression-parameter-estimates-via-matrix-algebra" class="section level2">
<h2>Regression Parameter Estimates via Matrix Algebra</h2>
<p>Now, having already derived identical estimators for the regression parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> several ways, your motivation to do the same thing yet another way may not be high.</p>
<p>But yes, really! We shall do it anyway. Why? For later topics, thinking about the regression equation as a matrix equation will prove helpful. Also, here’s a chance to see yet another application of linear algebra in all its glory.</p>
<div id="section-geometric-interpretation-of-a-linear-model" class="section level3">
<h3>Geometric Interpretation of a Linear Model</h3>
<p><em>Textbook Reference: FAStR2 p. 464 and Chapter 6.3.5</em></p>
<p>Remember our old friend, the sketch of the geometric interpretation of a linear model? <em>It’s about to come in handy.</em></p>
<p><img src="images/linear-model.png" width="600px" style="display: block; margin: auto;" /></p>
<p>Recall, our linear regression model in matrix notation was:</p>
<p><span class="math display">\[ \mathbf{y} = \mathbf{X}\mathbf{\beta} + \mathbf{\epsilon}\]</span></p>
<p>Where <span class="math inline">\(\mathbf{X}\)</span> is the model matrix and <span class="math inline">\(\mathbf{y}\)</span>, <span class="math inline">\(\mathbf{\beta}\)</span>, and <span class="math inline">\(\mathbf{\epsilon}\)</span> are the response, parameter, and residual vectors.</p>
<p>The sketch above indicates that the residual vector <span class="math inline">\(\mathbf{\epsilon} = \mathbf{y} - \mathbf{\hat{y}} = \mathbf{y} - \mathbf{X}\mathbf{\hat{\beta}}\)</span> is orthogonal to any vector in the <em>model space</em>.</p>
<p>So (as you can see) the residual vector <span class="math inline">\(\mathbf{y} - \mathbf{X}\mathbf{\hat{\beta}}\)</span> is orthogonal to the fit vector <span class="math inline">\(\mathbf{\hat{y}}\)</span>. But how did we know that the fit vector was <em>in</em> the model space to begin with? The fit vector <span class="math inline">\(\mathbf{\hat{y}}\)</span> is a linear combination of the columns of the model matrix <span class="math inline">\(\mathbf{X}\)</span>. The columns of the model matrix <span class="math inline">\(\mathbf{X}\)</span> are a basis for the model space (so – relevant to our current endeavor – they have to be in the model space, too). Whew! So what?</p>
<p>The residual vector will be orthogonal to any vector in the model space, so <span class="math inline">\(\mathbf{y} - \mathbf{X}\mathbf{\hat{\beta}} \perp \mathbf{x_{.j}}\)</span> for all <span class="math inline">\(j\)</span>. This means that, for all <span class="math inline">\(j\)</span>,</p>
<p><span class="math display">\[ \mathbf{x_{.j}} \cdot (\mathbf{y} - \mathbf{X}\mathbf{\hat{\beta}}) = 0 \]</span> Aha!</p>
<p>Rewriting this in matrix form, we have</p>
<p><span class="math display">\[ 0 = \mathbf{X}^{\top} (\mathbf{y} - \mathbf{X}\mathbf{\hat{\beta}})\]</span></p>
</div>
<div id="section-you-solve-for-mathbfhatbeta" class="section level3">
<h3>You Solve for <span class="math inline">\(\mathbf{\hat{\beta}}\)</span></h3>
<p><em>Text book reference: FAStR2 Chapter 6.3.5</em></p>
<p>We want to solve</p>
<p><span class="math display">\[ 0 = \mathbf{X}^{\top} (\mathbf{y} - \mathbf{X}\mathbf{\hat{\beta}})\]</span></p>
<p>For <span class="math inline">\(\mathbf{\beta}\)</span>, the vector of regression parameter estimates.</p>
<p><strong>Before you continue, give it a try.</strong></p>
<p>There are no tricky substitutions or anything like that - just follow through with the basic algebra. Solution is in the next section…</p>
</div>
<div id="section-we-solve-for-mathbfhatbeta" class="section level3">
<h3>We Solve for <span class="math inline">\(\mathbf{\hat{\beta}}\)</span></h3>
<p>We want to solve</p>
<p><span class="math display">\[ 0 = \mathbf{X}^{\top} (\mathbf{y} - \mathbf{X}\mathbf{\hat{\beta}})\]</span></p>
<p>For <span class="math inline">\(\mathbf{\beta}\)</span>, the vector of regression parameter estimates.</p>
<p>First, multiply through by <span class="math inline">\(\mathbf{X}^{\top}\)</span> on the right hand side:</p>
<p><span class="math display">\[ 0 = \mathbf{X}^{\top} \mathbf{y} - \mathbf{X}^{\top}\mathbf{X}\mathbf{\hat{\beta}}\]</span></p>
<p>Then, move the <span class="math inline">\(\mathbf{\beta}\)</span> term to the left hand side:</p>
<p><span class="math display">\[   \mathbf{X}^{\top}\mathbf{X}\mathbf{\hat{\beta}} = \mathbf{X}^{\top} \mathbf{y}\]</span></p>
<p>And finally, multiply both sides by <span class="math inline">\((\mathbf{X}^{\top}\mathbf{X})^{-1}\)</span> to get</p>
<p><span class="math display">\[ \mathbf{\hat{\beta}} = (\mathbf{X}^{\top}\mathbf{X})^{-1} \mathbf{X}^{\top} \mathbf{y}\]</span></p>
<p>Sweet!</p>
<p><em>Side Note: You may have been worried about it, so let me assure you that the inverse of <span class="math inline">\(\mathbf{X}^{\top}\mathbf{X}\)</span> will exist as long as the columns of <span class="math inline">\(\mathbf{X}\)</span> are linearly independent.</em></p>
</div>
<div id="section-putting-on-the-hat" class="section level3">
<h3>Putting on the Hat!</h3>
<p>The expression we just found:</p>
<p><span class="math display">\[ \mathbf{\hat{\beta}} = (\mathbf{X}^{\top}\mathbf{X})^{-1} \mathbf{X}^{\top} \mathbf{y}\]</span></p>
<p>can be combined with the definition of the fit vector <span class="math inline">\(\mathbf{\hat{y}} = \mathbf{X}\mathbf{\hat{\beta}}\)</span> to get an expression for <span class="math inline">\(\mathbf{\hat{y}}\)</span>, the fitted values, in terms of the data (<span class="math inline">\(\mathbf{y}\)</span> and <span class="math inline">\(\mathbf{X}\)</span>):</p>
<p><span class="math display">\[\mathbf{\hat{y}} = \mathbf{X}\mathbf{\hat{\beta}} = \mathbf{X}(\mathbf{X}^{\top}\mathbf{X})^{-1} \mathbf{X}^{\top} \mathbf{y}\]</span></p>
<p>The matrix <span class="math inline">\(\mathbf{H} = \mathbf{X}(\mathbf{X}^{\top}\mathbf{X})^{-1} \mathbf{X}^{\top}\)</span> is called the “hat” matrix because <em>it puts a hat on </em> <span class="math inline">\(\mathbf{y}\)</span>. It will come in handy in other ways in later modules.</p>
</div>
<div id="section-r-example" class="section level3">
<h3>R Example?</h3>
<p>We can use the estimators we just derived in R to find slope and intercept estimates for a small dataset.</p>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div><div class="panel panel-default">
<div data-label="why-small-1" class="tutorial-question panel-body">
<div id="why-small-1-answer_container" class="shiny-html-output"></div>
<div id="why-small-1-message_container" class="shiny-html-output"></div>
<div id="why-small-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div></p>
<p>We will use a tiny subset of the <code>bonobos</code> dataset as an example. You may recall the dataset from a recent test and problem set. Briefly, the dataset is from a <a href="https://royalsocietypublishing.org/doi/10.1098/rsbl.2019.0232">2019 paper by J.S. Martin and colleagues on bonobo face measurements</a>. The authors worked with 117 bonobos in European zoos and recorded data including their <code>Sex</code>, <code>Age</code> in years, <code>weight</code>, and some measurements about their face:</p>
<p><img src="images/bonobo-face-measures.jpg" width="350px" style="display: block; margin: auto;" /></p>
<p>Finally, they also measured each bonobo’s assertiveness score (<code>AssR</code>) and dominance score (<code>normDS</code>).</p>
<p>The dataset is at <a href="https://sldr.netlify.com/data/bonobo_faces.csv">https://sldr.netlify.com/data/bonobo_faces.csv</a> and you can read 10 observations from the dataset in to R by running:</p>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Name"],"name":[1],"type":["fctr"],"align":["left"]},{"label":["Group"],"name":[2],"type":["fctr"],"align":["left"]},{"label":["Sex"],"name":[3],"type":["fctr"],"align":["left"]},{"label":["Age"],"name":[4],"type":["int"],"align":["right"]},{"label":["fWHR"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["AssR"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["normDS"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["weight"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["orig.id"],"name":[9],"type":["chr"],"align":["left"]}],"data":[{"1":"Vifijo","2":"Planckendael","3":"Male","4":"18","5":"1.385714","6":"2.68","7":"2.165","8":"38.0","9":"9","_rn_":"14"},{"1":"Muhdeblu","2":"Wuppertal","3":"Female","4":"12","5":"1.364119","6":"2.62","7":"2.943","8":"36.5","9":"11","_rn_":"16"},{"1":"Kakowet","2":"Twycross","3":"Male","4":"32","5":"1.310127","6":"3.13","7":"1.682","8":"43.5","9":"43","_rn_":"74"},{"1":"Hortense","2":"Apenheul","3":"Female","4":"34","5":"1.317881","6":"3.05","7":"1.755","8":"40.0","9":"46","_rn_":"77"},{"1":"Mixi","2":"Frankfurt","3":"Female","4":"11","5":"1.826446","6":"4.12","7":"3.944","8":"36.0","9":"16","_rn_":"21"},{"1":"Eja","2":"Wuppertal","3":"Female","4":"22","5":"1.399533","6":"5.00","7":"1.536","8":"41.0","9":"52","_rn_":"83"},{"1":"Lina","2":"Planckendael","3":"Female","4":"27","5":"1.323834","6":"5.38","7":"1.722","8":"33.8","9":"26","_rn_":"49"},{"1":"Hortense","2":"Apenheul","3":"Female","4":"34","5":"1.291840","6":"3.05","7":"1.755","8":"40.0","9":"47","_rn_":"78"},{"1":"Kumbuka","2":"Apenheul","3":"Female","4":"13","5":"1.488706","6":"4.79","7":"3.131","8":"34.6","9":"33","_rn_":"59"},{"1":"Kakowet","2":"Twycross","3":"Male","4":"32","5":"1.401934","6":"3.13","7":"1.682","8":"43.5","9":"41","_rn_":"72"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>We might wonder whether size (as measured by <code>weight</code>) is a good predictor of the dominance score, <code>normDS</code>. Graphically:</p>
<pre class="r"><code>gf_point(normDS ~ weight, data = bonobos)</code></pre>
<p><img src="RegressionInference_files/figure-html/unnamed-chunk-4-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Of course, we know how to fit this model using <code>lm()</code> – or, we could use any of the expressions for the slope and intercept that we found in the previous module. Let’s use <code>lm()</code>:</p>
<pre><code>## 
## Call:
## lm(formula = normDS ~ weight, data = bonobos)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.20771 -0.28945 -0.01387  0.27096  1.32841 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  7.75581    2.58909   2.996   0.0172 *
## weight      -0.14278    0.06668  -2.141   0.0646 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6935 on 8 degrees of freedom
## Multiple R-squared:  0.3644, Adjusted R-squared:  0.2849 
## F-statistic: 4.586 on 1 and 8 DF,  p-value: 0.06464</code></pre>
<p>Or, if you want it to look prettier,</p>
<pre><code>## 
## % Table created by stargazer v.5.2.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
## % Date and time: Mon, Apr 13, 2020 - 4:06:58 AM
## \begin{table}[!htbp] \centering 
##   \caption{} 
##   \label{} 
## \begin{tabular}{@{\extracolsep{5pt}}lc} 
## \\[-1.8ex]\hline 
## \hline \\[-1.8ex] 
##  &amp; \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
## \cline{2-2} 
## \\[-1.8ex] &amp; normDS \\ 
## \hline \\[-1.8ex] 
##  weight &amp; $-$0.143$^{*}$ \\ 
##   &amp; (0.067) \\ 
##   &amp; \\ 
##  Constant &amp; 7.756$^{**}$ \\ 
##   &amp; (2.589) \\ 
##   &amp; \\ 
## \hline \\[-1.8ex] 
## Observations &amp; 10 \\ 
## R$^{2}$ &amp; 0.364 \\ 
## Adjusted R$^{2}$ &amp; 0.285 \\ 
## Residual Std. Error &amp; 0.694 (df = 8) \\ 
## F Statistic &amp; 4.586$^{*}$ (df = 1; 8) \\ 
## \hline 
## \hline \\[-1.8ex] 
## \textit{Note:}  &amp; \multicolumn{1}{r}{$^{*}$p$&lt;$0.1; $^{**}$p$&lt;$0.05; $^{***}$p$&lt;$0.01} \\ 
## \end{tabular} 
## \end{table}</code></pre>
<p>Either way, the parameter estimates are <span class="math inline">\(\beta_0 = 7.76\)</span> and <span class="math inline">\(\beta_1 = -0.143\)</span>.</p>
<p>We can compute these using</p>
<p><span class="math display">\[ \mathbf{\hat{\beta}} = (\mathbf{X}^{\top}\mathbf{X})^{-1} \mathbf{X}^{\top} \mathbf{y}\]</span></p>
<p>We just need to construct the model matrix <span class="math inline">\(\mathbf{X}\)</span>, and we’ll need R functions <code>t()</code> (matrix transpose), <code>solve()</code> (matrix inverse), and <code>%*%</code> (matrix multiplication).</p>
<p>First, construct the model matrix. Its first column should be all ones, and its second column should be the <code>weight</code> data from <code>bonobos</code>.</p>
<div class="tutorial-exercise" data-label="get-X" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6,"fig.height":2.5,"fig.retina":2,"fig.align":"center","fig.keep":"high","fig.show":"asis","out.width":576,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="get-X-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>X &lt;- cbind(rep(1, nrow(bonobos)),
           bonobos$weight)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="get-X-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># a shortcut way:
X &lt;- model.matrix(lm(normDS ~ weight, data = bonobos))</code></pre>
</div>
<p>Next, use our formula for <span class="math inline">\(\mathbf{\beta}\)</span> to compute the parameter estimates.</p>
<div class="tutorial-exercise" data-label="get-betas" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6,"fig.height":2.5,"fig.retina":2,"fig.align":"center","fig.keep":"high","fig.show":"asis","out.width":576,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="get-betas-solution" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>betas &lt;- solve( t(X) %*% X ) %*% t(X) %*% bonobos$normDS
betas</code></pre>
</div>
<p><strong>Hurrah! It works.</strong></p>
<p>Finally, find the hat matrix <span class="math inline">\(\mathbf{H} \mathbf{X}(\mathbf{X}^{\top}\mathbf{X})^{-1} \mathbf{X}^{\top}\)</span> and use it to compute the fitted values <span class="math inline">\(\mathbf{\hat{y}}\)</span>. Compare these the R’s results from <code>fitted()</code>.</p>
<div class="tutorial-exercise" data-label="get-fitted" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6,"fig.height":2.5,"fig.retina":2,"fig.align":"center","fig.keep":"high","fig.show":"asis","out.width":576,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="get-fitted-solution" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>H &lt;- X %*% solve( t(X) %*% X ) %*% t(X) 
y_hat &lt;- H %*% bonobos$normDS
cbind(y_hat, fitted(lm(normDS ~ weight, data = bonobos)))</code></pre>
</div>
</div>
</div>
<div id="section-lets-do-it-again" class="section level2">
<h2>Let’s Do It Again</h2>
<p>As a nice recap, I encourage you to check out a video by Prof. Fishback (from GVSU’s Mathematics Department). Made for a linear algebra class, it reviews the linear regression model basics and derives the <em>normal equation</em> for linear regression (i.e., the estimates for <span class="math inline">\(\mathbf{\hat{\beta}}\)</span>) from the perspective of linear algebra students applying their know-how to stats, rather than stats students using linear algebra.</p>
<p><strong>Challenge: Prof Fishback makes one tiny error in the video (it is inconsequential, in terms of the linear algebra and this derivation). Can you spot it? Email me your answer for a few homework points.</strong></p>
<p><img src="https://www.youtube.com/watch?v=gGWsW9BaeCY" width="400" /></p>
<p>(You can also <a href="https://www.youtube.com/watch?v=gGWsW9BaeCY">watch directly on YouTube</a> if you prefer.</p>
</div>
<div id="section-sampling-distributions-of-estimators" class="section level2">
<h2>Sampling Distributions of Estimators</h2>
<p>We have now derived (the same) estimators for the regression slope and intercept parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, nearly <em>ad infinitum</em>. We also talked a little bit about an estimator for <span class="math inline">\(\sigma\)</span>, the standard deviation of the residuals.</p>
<p>But none of this gets us very close to our goal of <strong>inference</strong> about these regression parameters – for that, we need to consider our estimators as random variables and determine their variances.</p>
<p>(It would also be nice to find their expectations and see that they match the true parameter values; that is, <span class="math inline">\(E(\hat{\beta_0}) = \beta_0\)</span> and <span class="math inline">\(E(\hat{\beta_1}) = \beta_1\)</span>; in other words, to show our estimators are unbiased.)</p>
<p>If we get the <em>expectation</em> and <em>variance</em> of an estimator, we’ve characterized its <em>sampling distribution</em> (which is just what we need to do a CI or test).</p>
<p>To pursue this project, we will consider our estimators <span class="math inline">\(\hat{\beta}\)</span> as random variables. To emphasize this, in section 6.4 of your book, we use the notation <span class="math inline">\(B_0\)</span> for <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(B_1\)</span> for <span class="math inline">\(\hat{\beta}_1\)</span>. But whichever notation is used, they are the same two quantities.</p>
</div>
<div id="section-the-book-is-better" class="section level2">
<h2>The Book is Better?</h2>
<p>Please note that the next few sections of this tutorial (which consider the expectation and variance of the slope and intercept, and an unbiased estimator for the residual standard deviation) <em>take a different approach from the FAStR book</em>.</p>
<p>The approach in the book is arguably more elegant, but perhaps also less intuitive. And in the spirit of this chapter (and, well, math…) it’s always interesting to come at the same problem several ways.</p>
<p>Each section will refer to the corresponding section of FAStR, which you can expect to arrive at the same solution by a different route.</p>
<div id="section-notation-note" class="section level3">
<h3>Notation Note</h3>
<p><em>One last note: I have carefully curated the videos included in the next sections to find you the ones I think are most clear and concise (and correct). (There are others out there that are…not.) Some have small notation differences that will be highlighted to avoid confusion as much as possible - I think this is more efficient than making brand new videos just for small notation changes.</em></p>
</div>
</div>
<div id="section-sampling-distribution-of-the-regression-slope" class="section level2">
<h2>Sampling Distribution of the Regression Slope</h2>
<p><em>Text book reference: FAStR Chapter 6.4.2</em></p>
<p>First, let’s consider the regression slope and investigate its sampling distribution (in other words, its mean and variance).</p>
<p>Why slope first? Well, it’s everyone’s favorite…honestly, it kind of is. The slope is the parameter (of our three) that best measures the relationship between predictor and response variables, and measuring that relationship is a main goal of most regression modelling. So slopes rule!</p>
<p>For this first one, we’ll return to the non-matrix-notation version of our regression equation. Here we go!</p>
<p><img src="https://www.youtube.com/watch?v=rODUBTRUV0U" width="400" /></p>
<p>(You can also <a href="https://www.youtube.com/watch?v=rODUBTRUV0U">watch directly on YouTube</a> if you prefer.</p>
<p>To sum up:</p>
<ul>
<li>Our estimator <span class="math inline">\(B_1 = \hat{\beta}}_1\)</span> is unbiased (its expected value is <span class="math inline">\(\beta_1\)</span>). What a relief!</li>
<li>The standard deviation of <span class="math inline">\(B_1\)</span> is <span class="math inline">\(\frac{\sigma}{\sqrt{\sum(x_i - \bar{x})^2}}\)</span> or, in matrix notation, <span class="math inline">\(\frac{\sigma}{\mid \mathbf{x} - \mathbf{\bar{x}}\mid}\)</span>.</li>
<li>Putting them together, the sampling distribution of <span class="math inline">\(B_1\)</span> is <span class="math inline">\(B_1 \sim N(\beta_1, \frac{\sigma}{\sqrt{\sum(x_i - \bar{x})^2}})\)</span>.</li>
<li><em>Note that at the end of the video, it says <span class="math inline">\(\hat{\beta}_1 \sim N(\beta_1, \frac{\sigma^2}{{\sum(x_i - \bar{x})^2}})\)</span>, but that is using the notation <span class="math inline">\(N(\mu, \sigma^2)\)</span> (mean and variance), where we always use <span class="math inline">\(N(\mu, \sigma)\)</span> (mean and standard deviation).</em></li>
</ul>
</div>
<div id="section-sampling-distribution-of-the-intercept-and-slope" class="section level2">
<h2>Sampling Distribution of the Intercept (and Slope)</h2>
<p><em>Text book reference: FAStR Chapter 6.4.3</em></p>
<p>Now, let’s consider variance for the intercept estimator. Well…actually, this time, we’ll work in matrix notation, so we’ll actually get the variance of the slope (again), too.</p>
<p>(<em>For a demonstration that <span class="math inline">\(B_0 = \hat{\beta}_0\)</span> is an unbiased estimator of <span class="math inline">\(\beta_0\)</span>, see section 6.4.3 of the book for details. Or, check out the <a href="https://www.youtube.com/watch?v=h2NcWHiayJI&amp;t=36s">optional additional video</a>.</em>)</p>
<p>Notation notes:</p>
<ul>
<li>A capital letter with a tilde (<span class="math inline">\(\sim\)</span>) under it means a non-stochastic matrix</li>
<li>A capital letter with a bar under it means a stochastic matrix</li>
<li>A lower case letter with a bar under it means a vector</li>
<li><span class="math inline">\(u\)</span> refers to the residuals</li>
<li>A tick mark (“prime”) after a matrix indicates a matrix transpose</li>
</ul>
<p><img src="https://www.youtube.com/watch?v=11J0M7WBMy8" width="400" /></p>
<p>(You can also <a href="https://www.youtube.com/watch?v=11J0M7WBMy8">watch directly on YouTube</a> if you prefer.</p>
<p>This is short and sweet and lovely, which is why I showed it to you. But it’s also a bit unsatisfying in that it’s not straightforward to pull out specific expressions for the variances of the two <span class="math inline">\(\beta\)</span>s (slope and intercept).</p>
<div id="section-varb0-non-matrix-version" class="section level3">
<h3>Var(B0), non-matrix version</h3>
<p>Here is a sketch of the derivation of the expression for the variance of <span class="math inline">\(B_0\)</span>, not in matrix form:</p>
<p>We know from the regression equation that</p>
<p><span class="math display">\[B_0 = \bar{Y} - B_1\bar{x}\]</span> Notice that (some of these are from 343):</p>
<ul>
<li><span class="math inline">\(B_0\)</span> and <span class="math inline">\(\bar{Y}\)</span> are independent and <span class="math inline">\(\bar{x}\)</span> is a constant conditional on the data</li>
<li>The variance of the difference of two independent random variables is the difference of their variances</li>
<li>The variance of the product of a random variable times a constant <span class="math inline">\(a\)</span> increases the variance by a factor of <span class="math inline">\(a^2\)</span>.</li>
<li>The variance of a mean is <span class="math inline">\(\frac{\sigma^2}{n}\)</span> (its standard deviation is <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>)</li>
</ul>
<p>Using all this, we can derive <span class="math inline">\(Var(B_0)\)</span>. Give it a go before clicking to the next page…</p>
</div>
<div id="section-derivation" class="section level3">
<h3>Derivation</h3>
<p><span class="math display">\[ Var(B_0) = Var(\bar{Y} - B_1\bar{x}) =\]</span></p>
<p><span class="math display">\[ Var(\bar{Y}) - \bar{x}^2 Var(B_1)\]</span></p>
<p>Then, recalling that <span class="math inline">\(Var(B_1) = \frac{\sigma^2}{{\sum(x_i - \bar{x})^2}}\)</span>,</p>
<p><span class="math display">\[ \frac{\sigma^2}{n} -  \frac{\bar{x}^2\sigma^2}{{\sum(x_i - \bar{x})^2}} = \]</span></p>
<p><span class="math display">\[ \sigma^2 \bigg{(}\frac{1}{n} - \frac{\bar{x}^2}{{\sum(x_i - \bar{x})^2}}\bigg{)}\]</span></p>
<p>So the corresponding standard deviation is (taking the square root)</p>
<p><span class="math display">\[ \sigma \sqrt{\bigg{(}\frac{1}{n} - \frac{\bar{x}^2}{{\sum(x_i - \bar{x})^2}}\bigg{)}} = \sigma \sqrt{\bigg{(}\frac{1}{n} - \frac{\bar{x}^2}{{S_{xx}}}\bigg{)}}\]</span></p>
<p>So the sampling distribution of <span class="math inline">\(B_0\)</span> is <span class="math inline">\(N(\beta_0, \sigma \sqrt{\bigg{(}\frac{1}{n} - \frac{\bar{x}^2}{{S_{xx}}}\bigg{)}})\)</span>.</p>
</div>
</div>
<div id="section-estimator-for-sigma2" class="section level2">
<h2>Estimator for <span class="math inline">\(\sigma^2\)</span></h2>
<p><em>Textbook reference: FAStR Chapter 6.4.5</em></p>
<p>In the last module, we noted that an apparently natural estimator for the residual standard deviation is the MLE,</p>
<p><span class="math display">\[\hat{\sigma}_{MLE} = \frac{\sum_{i=1}^{n}e_i}{n} = \frac{SSE}{n}\]</span></p>
<p>You were forewarned, though, that this estimator is acutally biased, and we want instead</p>
<p><span class="math display">\[\hat{\sigma} = S^2 = \frac{\sum_{i=1}^{n}e_i}{(n-2)} = \frac{SSE}{(n-2)}\]</span></p>
<p><strong>How? Why?</strong> Watch and see…</p>
<p><em>As in the earlier video, tildes and bars under letters indicate matrices/vectors, capital rather than small letters mean matrices, and <span class="math inline">\(u\)</span> is used for the residuals.</em></p>
<p><img src="https://www.youtube.com/watch?v=H8tAmuk1lDc" width="400" /></p>
<p>(You can also <a href="https://www.youtube.com/watch?v=H8tAmuk1lDc">watch directly on YouTube</a> if you prefer.</p>
<p>OK, great! We now have all the tools we need to figure out how to construct CIs and carry out tests.</p>
</div>
<div id="section-inference" class="section level2">
<h2>INFERENCE</h2>
<p><em>Textbook reference: FAStR Chapter 6.4.5</em></p>
<p>Finally, we are near our goal: establish a method to generate confidence intervals and carry out tests for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, the intercept and slope.</p>
<div id="section-slope" class="section level3">
<h3>Slope</h3>
<p>We found that <span class="math inline">\(B_1 \sim N(\beta_1, \frac{\sigma}{\sqrt{\sum(x_i - \bar{x})^2}})\)</span>. But we can’t stop there, because <span class="math inline">\(\sigma\)</span> is another parameter of the model; we don’t know it’s true value, only its estimate <span class="math inline">\(\hat{\sigma}\)</span>.</p>
<p>We begin by standardizing <span class="math inline">\(B_1\)</span> to obtain a random variable with a standard normal distribution:</p>
<p><span class="math display">\[ \frac{B_1 - \beta_1}{\sigma \ \sqrt{\sum(x_i - \bar{x})^2}} \sim N(0,1)\]</span></p>
<p>Remind you of anything a bit? Hypothesis tests for a mean, perhaps?</p>
</div>
<div id="section-more-about-sigma" class="section level3">
<h3>More about <span class="math inline">\(\sigma\)</span></h3>
<p>We know that <span class="math inline">\(\frac{SSE}{\sigma^2} \sim Chisq(n - 2)\)</span> (see FAStR page 483), and since <span class="math inline">\(S^2 = \frac{SSE}{(n-2)}\)</span>, <span class="math inline">\(\frac{S^2 (n-2)}{\sigma^2} \sim Chisq(n-2)\)</span>.</p>
<p>So what is the distribution of</p>
<p><span class="math display">\[  \frac{B_1 - \beta_1}{S^2 \ \sqrt{\sum(x_i - \bar{x})^2}} \]</span></p>
<p>Here we will do some rearrangement that will make sense later. First, divide both top and bottom by <span class="math inline">\(\frac{\sigma}{\sqrt{\sum(x_i - \bar{x})^2}}\)</span> to get:</p>
<p><span class="math display">\[ \frac{ \frac{B_1 - \beta_1}{\sigma^2 \ \sqrt{\sum(x_i - \bar{x})^2}}}
{\frac{S}{\sigma}}\]</span></p>
<p>Next, multiply the denominator by $ 1 = $:</p>
<p><span class="math display">\[ \frac{ \frac{B_1 - \beta_1}{\sigma^2 \ \sqrt{\sum(x_i - \bar{x})^2}}}
{\frac{S\sqrt{n-2}}{\sigma} / \sqrt{n-2}}\]</span></p>
<p><strong>Any</strong> idea why we chose to do <em>that</em>?</p>
</div>
</div>
<div id="section-normal-chi-square-and-t-distributions" class="section level2">
<h2>Normal, Chi-square, and t-distributions</h2>
<p>Remember where the t-distribution came from?</p>
<p>A t-distribution with <span class="math inline">\(d\)</span> degrees of freedom is</p>
<p><span class="math display">\[\frac{z}{\sqrt{\frac{\chi ^ 2}{d}}}\]</span></p>
<p>Where <span class="math inline">\(z\)</span> is a random variable with a standard normal distribution, and <span class="math inline">\(\chi^2\)</span> is a random variable with a chi-square distribution with <span class="math inline">\(d\)</span> degrees of freedom.</p>
<p><em>Ahhhhh, now it makes sense!</em></p>
<p><span class="math display">\[ \frac{ \frac{B_1 - \beta_1}{\sigma^2 \ \sqrt{\sum(x_i - \bar{x})^2}}}
{\frac{S\sqrt{n-2}}{\sigma} / \sqrt{n-2}} \sim t(\text{df} = n-2)\]</span></p>
<p><strong>THIS. IS. GREAT.</strong> It means that we can use almost the same procedure we used for a one-sample t-test (or interval) for a mean, but for the regression slope. We just have to use the standard error <span class="math inline">\(\frac{s}{ \sqrt{\sum(x_i - \bar{x})^2}}\)</span> instead of the SE for a mean (which was <span class="math inline">\(\frac{s}{\sqrt{n}}\)</span>), and adjust the degrees of freedom to match the number of rows in the model matrix <span class="math inline">\(\mathbf{X}\)</span> (minus 2).</p>
<p>The only hardship now is that it’s kind of a pain to compute</p>
<p><span class="math display">\[SE(\hat{\beta_1}) = \frac{s}{\sqrt{\sum(x_i - \bar{x})^2}} = \frac{\sqrt{MSE}}{\sqrt{S_{xx}}} = \frac{SE(\text{residuals})}{\sqrt{S_{xx}}}\]</span> There are a lot of ways to write it but whichever one you choose it’s a lot of tapping away on a calculator! Luckily, we have R functions to do all that work for us.</p>
<p>In fact, the <code>summary()</code> of an <code>lm()</code> fit includes these standard errors in the coefficient table, labelled “Std. Error”.</p>
<pre class="r"><code>bm &lt;- lm(normDS ~ weight, data = bonobos)
summary(bm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = normDS ~ weight, data = bonobos)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.20771 -0.28945 -0.01387  0.27096  1.32841 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  7.75581    2.58909   2.996   0.0172 *
## weight      -0.14278    0.06668  -2.141   0.0646 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6935 on 8 degrees of freedom
## Multiple R-squared:  0.3644, Adjusted R-squared:  0.2849 
## F-statistic: 4.586 on 1 and 8 DF,  p-value: 0.06464</code></pre>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div><div class="panel panel-default">
<div data-label="get-bonobo-se-1" class="tutorial-question panel-body">
<div id="get-bonobo-se-1-answer_container" class="shiny-html-output"></div>
<div id="get-bonobo-se-1-message_container" class="shiny-html-output"></div>
<div id="get-bonobo-se-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div></p>
<div id="section-a-confidence-interval" class="section level3">
<h3>A Confidence Interval</h3>
<p>So, after all that, we can find a CI for a regression slope according to:</p>
<p><span class="math display">\[ B_1 \pm t_*SE(B_1)\]</span></p>
<p>Where <span class="math inline">\(t_*\)</span> is a critical value from a <span class="math inline">\(t(n-2)\)</span> distribution.</p>
<p>As an example, find a 95% CI for the slope of our <code>bonobo</code> regression model.</p>
<div class="tutorial-exercise" data-label="bonobo-ci" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6,"fig.height":2.5,"fig.retina":2,"fig.align":"center","fig.keep":"high","fig.show":"asis","out.width":576,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="bonobo-ci-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>bm &lt;- lm(normDS ~ weight, data= bonobos)
summary(bm)
CI95 &lt;- -0.14278 + c(-1,1) * qt(0.975, df = nrow(bonobos) - 2) * 0.06668
CI95</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="bonobo-ci-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># a shortcut:
bm &lt;- lm(normDS ~ weight, data= bonobos)
confint(bm, &quot;weight&quot;, level = 0.95)</code></pre>
</div>
<p>Notice the shortcut – R function <code>confint()</code> returns CIs (with a default confidence level of 95%).</p>
</div>
<div id="section-a-t-test" class="section level3">
<h3>A t-test</h3>
<p>We can also test the null hypothesis <span class="math inline">\(H_0: \beta_1 = \beta_{1\text{null}}\)</span> (where <span class="math inline">\(\beta_{1\text{null}}\)</span> is some hypothetical slope value of interest) using the standardized test statistic</p>
<p><span class="math display">\[ t = \frac{\hat{\beta}_1 - \beta_{1\text{null}}}{SE(\hat{\beta}_1)}\]</span></p>
<p>The most common value for <span class="math inline">\(\beta_{1\text{null}}\)</span> is <span class="math inline">\(0\)</span>, because if <span class="math inline">\(\beta_1 = 0\)</span> that means that there is <em>no</em> relationship between the predictor and response and the predictor is useless as a predictor. If we can reject that null hypothesis, we can conclude that the predictor <em>does</em> have some utility.</p>
<p>To practice, carry out a two-sided test of <span class="math inline">\(H_0: \beta_1 = 0\)</span> for the <code>bonobo</code> regression.</p>
<div class="tutorial-exercise" data-label="bonobo-test" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6,"fig.height":2.5,"fig.retina":2,"fig.align":"center","fig.keep":"high","fig.show":"asis","out.width":576,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="bonobo-test-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>bm &lt;- lm(normDS ~ weight, data= bonobos)
summary(bm)
t_stat &lt;- (-0.14278 - 0) / (0.06668)
p_val &lt;- 2 * pt(t_stat, df = nrow(bonobos) - 2, lower.tail = TRUE)
p_val</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="bonobo-test-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#shortcut: just use model summary
bm &lt;- lm(normDS ~ weight, data= bonobos)
summary(bm)</code></pre>
</div>
<p>A shortcut: Notice that this p-value is already in the model summary (in the last column of the coefficient table, labelled “Pr(<span class="math inline">\(&gt;\vert\)</span>t<span class="math inline">\(\vert\)</span>)”). Note that for simple linear regression, the p-value reported at the very end of the model summary is the same (although with a different test stat and df) – this is <em>only</em> true when there is only one predictor. Stay tuned for later modules to know that that thing at the end is, but for now, get used to using the info in the coefficient table.</p>
</div>
</div>
<div id="section-poor-intercept" class="section level2">
<h2>Poor intercept</h2>
<p>A nearly identical argument demonstrates that we can use t-tests and intervals for the intercept, too. We just need to use the appropriate standard error estimate (which, luckily, R again reports for us).</p>
<p>The details are not included here because they really are just about the same, and also CIs and tests of hypotheses about intercept values are generally of less practical interest than the corresponding ones about slopes.</p>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
# library(checkr)
# library(statPREP)
library(tibble)
library(ggformula)
library(mosaic)
#library(fastR)
#library(fastR2)
library(maxLik)
theme_set(theme_bw(base_size=16))
# knitr::opts_chunk$set(exercise.checker = checkr::checkr_tutor)
knitr::opts_chunk$set(
  echo = FALSE,
  fig.align = "center",
  fig.width = 6, fig.height = 2.5)
tutorial_options(exercise.eval = FALSE)

set.seed(14)
bonobos <- read.csv('http://sldr.netlify.com/data/bonobo_faces.csv') %>%
  na.omit() %>%
  sample(size = 10)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "why-small-1",     question = structure("Why do you think we are using a small dataset for this example?", html = TRUE, class = c("html",     "character")), answers = list(structure(list(id = "lnr_ans_db82be9",         option = "All those matrix inversions and multiplications will cause trouble if n is large -- slow to compute and prone to round-off error.",         value = "All those matrix inversions and multiplications will cause trouble if n is large -- slow to compute and prone to round-off error.",         label = structure("All those matrix inversions and multiplications will cause trouble if n is large -- slow to compute and prone to round-off error.", html = TRUE, class = c("html",         "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer",     "tutorial_quiz_answer")), structure(list(id = "lnr_ans_bd5bfa5",         option = "There is no way to do matrix multiplication and inversion in R, so you have to write a lot of code by hand.",         value = "There is no way to do matrix multiplication and inversion in R, so you have to write a lot of code by hand.",         label = structure("There is no way to do matrix multiplication and inversion in R, so you have to write a lot of code by hand.", html = TRUE, class = c("html",         "character")), correct = FALSE, message = structure("Nah, don&#39;t be silly! Of course you can do it. Not very efficiently for huge matrices, but the functions exist.", html = TRUE, class = c("html",         "character"))), class = c("tutorial_question_answer",     "tutorial_quiz_answer")), structure(list(id = "lnr_ans_5a64bde",         option = "It is easier to see what is going on and understand what you are doing with a small dataset.",         value = "It is easier to see what is going on and understand what you are doing with a small dataset.",         label = structure("It is easier to see what is going on and understand what you are doing with a small dataset.", html = TRUE, class = c("html",         "character")), correct = FALSE, message = structure("True, but not the main reason in this case...try again?", html = TRUE, class = c("html",         "character"))), class = c("tutorial_question_answer",     "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html",     "character")), try_again = structure("Try Again", html = TRUE, class = c("html",     "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html",     "character")), try_again = structure("Incorrect", html = TRUE, class = c("html",     "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html",     "character")), message = NULL, post_message = NULL), ids = list(        answer = "why-small-1-answer", question = "why-small-1"),     loading = structure("<strong>Loading:<\u002fstrong> \nWhy do you think we are using a small dataset for this example?\n<br/><br/><br/>", html = TRUE, class = c("html",     "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1446057684.32663, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-get-X-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-get-X-code-editor`)), session)
output$`tutorial-exercise-get-X-output` <- renderUI({
  `tutorial-exercise-get-X-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-get-betas-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-get-betas-code-editor`)), session)
output$`tutorial-exercise-get-betas-output` <- renderUI({
  `tutorial-exercise-get-betas-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-get-fitted-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-get-fitted-code-editor`)), session)
output$`tutorial-exercise-get-fitted-output` <- renderUI({
  `tutorial-exercise-get-fitted-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "get-bonobo-se-1",     question = structure("What is the SE(slope) for the regression to predict normDS as a function of weight for our small bonobo dataset?", html = TRUE, class = c("html",     "character")), answers = list(structure(list(id = "lnr_ans_db82be9",         option = "0.06668", value = "0.06668", label = structure("0.06668", html = TRUE, class = c("html",         "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer",     "tutorial_quiz_answer")), structure(list(id = "lnr_ans_bd5bfa5",         option = "-0.1428", value = "-0.1428", label = structure("-0.1428", html = TRUE, class = c("html",         "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer",     "tutorial_quiz_answer")), structure(list(id = "lnr_ans_5a64bde",         option = "0.6935", value = "0.6935", label = structure("0.6935", html = TRUE, class = c("html",         "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer",     "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ac622da",         option = "-2.14", value = "-2.14", label = structure("-2.14", html = TRUE, class = c("html",         "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer",     "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html",     "character")), try_again = structure("Try Again", html = TRUE, class = c("html",     "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html",     "character")), try_again = structure("Incorrect", html = TRUE, class = c("html",     "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html",     "character")), message = NULL, post_message = NULL), ids = list(        answer = "get-bonobo-se-1-answer", question = "get-bonobo-se-1"),     loading = structure("<strong>Loading:<\u002fstrong> \nWhat is the SE(slope) for the regression to predict normDS as a function of weight for our small bonobo dataset?\n<br/><br/><br/>", html = TRUE, class = c("html",     "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1828728882.64843, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-bonobo-ci-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-bonobo-ci-code-editor`)), session)
output$`tutorial-exercise-bonobo-ci-output` <- renderUI({
  `tutorial-exercise-bonobo-ci-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-bonobo-test-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-bonobo-test-code-editor`)), session)
output$`tutorial-exercise-bonobo-test-output` <- renderUI({
  `tutorial-exercise-bonobo-test-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","broom","checkmate","colorspace","compiler","crayon","crosstalk","datasets","digest","dplyr","ellipsis","evaluate","farver","fastmap","generics","ggdendro","ggforce","ggformula","ggplot2","ggrepel","ggstance","glue","graphics","grDevices","grid","gridExtra","gtable","hms","htmltools","htmlwidgets","httpuv","jsonlite","knitr","labeling","later","lattice","lazyeval","leaflet","learnr","lifecycle","magrittr","markdown","MASS","Matrix","maxLik","methods","mime","miscTools","mosaic","mosaicCore","mosaicData","munsell","nlme","pillar","pkgconfig","polyclip","promises","purrr","R6","Rcpp","readr","rlang","rmarkdown","rprojroot","sandwich","scales","shiny","splines","stargazer","stats","stringi","stringr","tibble","tidyr","tidyselect","tools","tweenr","utils","vctrs","withr","xfun","xtable","yaml","zoo"]},{"type":"character","attributes":{},"value":["0.2.1","1.1.5","3.6.3","0.5.5","2.0.0","1.4-1","3.6.3","1.3.4","1.0.0","3.6.3","0.6.25","0.8.5","0.3.0","0.14","2.0.3","1.0.1","0.0.2","0.1-20","0.3.1","0.9.4","3.3.0","0.8.2","0.3.3","1.3.2","3.6.3","3.6.3","3.6.3","2.3","0.3.0","0.5.3","0.4.0","1.5.1","1.5.2","1.6.1","1.28","0.3","1.0.0","0.20-38","0.2.2","2.0.3","0.10.1","0.2.0","1.5","1.1","7.3-51.5","1.2-18","1.3-8","3.6.3","0.9","0.6-26","1.6.0","0.6.0","0.17.0","0.5.0","3.1-144","1.4.3","2.0.3","1.10-0","1.1.0","0.3.3","2.4.1","1.0.4","1.3.1","0.4.5","2.1","1.3-2","2.5-1","1.1.0","1.4.0.2","3.6.3","5.2.2","3.6.3","1.4.6","1.4.0","2.1.3","1.0.2","1.0.0","3.6.3","1.0.1","3.6.3","0.2.4","2.1.2","0.12","1.8-4","2.2.1","1.8-7"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Inference for Simple Linear Regression</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
