<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="true" />
<meta name="allow-skip" content="true" />
<meta name="learnr-version-prerender" content="0.10.1.9019" />

<title>Logistic Regression (and Friends)</title>

<!-- header-includes START -->
<!-- HEAD_CONTENT -->
<!-- header-includes END -->
<!-- HEAD_CONTENT -->

<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>


<!-- taken from https://github.com/rstudio/rmarkdown/blob/de8a9c38618903627ca509f5401d50a0876079f7/inst/rmd/h/default.html#L293-L343 -->
<!-- tabsets -->
<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>
<!-- end tabsets -->


</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-learning-outcomes" class="section level2">
<h2>Learning Outcomes</h2>
<p>This module introduces logistic regression, which is a generalization of linear regression in which the <em>response</em> variable is a categorical variable with two possible values (often thought of as “successes” and “failures”).</p>
<p>By the end of the module you will:</p>
<ol style="list-style-type: decimal">
<li>Be familiar with the regression equations for logistic regression (and its relatives, probit and complementary log-log regression)</li>
<li>Derive an expression for the likelihood of a dataset, given a logistic regression model</li>
<li>Fit a logistic regression model using MLE and <code>maxLik()</code></li>
<li>Fit a logistic (or probit or c-log-log) regression model using <code>glm()</code></li>
<li>Interpret logistic regression slope values in terms of (log) odds ratios</li>
<li>Make inferences about the logistic regression slope parameter using Wald and likelihood-based CIs and tests</li>
</ol>
<p><em>These materials come from your text book, FAStR2 Chapter 6.8.</em></p>
</div>
<div id="section-more-transformations" class="section level2">
<h2>More Transformations</h2>
<p><img src="https://youtu.be/YS_BUn8uot8" width="400" /></p>
<p>(You can also <a href="https://youtu.be/YS_BUn8uot8">watch directly on YouTube</a> if you prefer).</p>
</div>
<div id="section-motivation-bonobos-again" class="section level2">
<h2>Motivation: Bonobos Again</h2>
<p><img src="https://youtu.be/K43eJcVd21A" width="400" /></p>
<p>(You can also <a href="https://youtu.be/K43eJcVd21A">watch directly on YouTube</a> if you prefer).</p>
<p>Well, there must be a solution to this problem, or we wouldn’t be here. Before you continue, see if you can use the clues you have already to come up with a strategy to <em>modify the linear regression equation</em> to make it work for a categorical predictor.</p>
</div>
<div id="section-probabilities" class="section level2">
<h2>Probabilities!</h2>
<p>If you guessed the probabilities would be a key to our strategy to make regression work for categorical responses, give yourself a pat on the back!</p>
<iframe src="https://giphy.com/embed/9Q249Qsl5cfLi" width="480" height="366" frameBorder="0" class="giphy-embed" allowFullScreen>
</iframe>
<p>
<a href="https://giphy.com/gifs/pat-patting-9Q249Qsl5cfLi">via GIPHY</a>
</p>
<p>The first, and most key, step to making this work is to focus, not on the values of the categorical variable, but on the process generating them.</p>
<p>Our variable has two possible values; let’s consider one of them to be a “success” (here, in our example, maybe being “Female” is “success”). It makes sense to posit that the data-generating process produces “successes” (observations that are “Female”) with some probability <span class="math inline">\(p\)</span>. Maybe <span class="math inline">\(p\)</span> is constant, or perhaps it depends on some other variable(s) (like, oh, I don’t know…<code>fWHR</code>?)</p>
<p>Now, all we have to do is work out the details.</p>
</div>
<div id="section-logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<p><img src="https://youtu.be/etIlztmozs8" width="400" /></p>
<p>(You can also <a href="https://youtu.be/etIlztmozs8">watch directly on YouTube</a> if you prefer).</p>
<p>Now that we have our model, we just have to figure out how to fit it to the data…we’ll use maximum likelihood estimation.</p>
</div>
<div id="section-logistic-regression-in-r-glm" class="section level2">
<h2>Logistic Regression in R: glm()</h2>
<p>First, the easy way - letting R do all the work.</p>
<p>We use function <code>glm()</code> (for “generalized linear model”), specifying the model family as <code>"binomial"</code> with a <code>"logit"</code> <strong>link function</strong> (the transformation that relates the response variable to the linear model).</p>
<p>For example, with our bonobos:</p>
<pre class="r"><code>bonobo_logit &lt;- glm(Sex ~ fWHR, data = bonobos,
                    family = binomial(link = &#39;logit&#39;))
summary(bonobo_logit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Sex ~ fWHR, family = binomial(link = &quot;logit&quot;), 
##     data = bonobos)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5427  -0.9531  -0.8238   1.2331   1.8658  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)   -4.388      2.138  -2.053   0.0401 *
## fWHR           2.716      1.448   1.876   0.0607 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 91.365  on 67  degrees of freedom
## Residual deviance: 87.584  on 66  degrees of freedom
## AIC: 91.584
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>(If we did want a probit or complementary log-log model instead, we would just use <code>family = binomial(link = 'probit')</code> or <code>family = binomial(link = 'cloglog')</code>, and the rest would stay the same.)</p>
<div id="section-fitted-model-equation" class="section level3">
<h3>Fitted Model Equation</h3>
<p>So the equation of our fitted model is:</p>
<p><span class="math display">\[ logit(p_i) = log \bigg{(} \frac{p_i}{(1-p_i)} \bigg{)} = -4.388 + 2.716 x_i\]</span></p>
<p><span class="math display">\[ y_i \sim Binom(1, p_i) = Binom\bigg{(}1, \frac{e^{-4.388 + 2.716 x_i}}{(1 + e^{-4.388 + 2.716 x_i})}\bigg{)}\]</span></p>
</div>
<div id="section-probability-of-what" class="section level3">
<h3>Probability of what?</h3>
<p>In applications, it is really important to know how a “success” has been defined in order to interpret the fitted model. Here, is <span class="math inline">\(p\)</span> the probability of being “Male”, or “Female”?</p>
<p>In R (likely because people often code binary variables with values 0 for “failure” and 1 for “success”), the “success” is usually the <em>second</em> possible value of the categorical variable, sorting the values in alphanumeric order.</p>
<p>We can check like so:</p>
<pre class="r"><code>levels(factor(bonobos$Sex))</code></pre>
<pre><code>## [1] &quot;Female&quot; &quot;Male&quot;</code></pre>
<p>The <strong>second</strong> one is the one R defines as a “success”, so in our model before, <span class="math inline">\(p\)</span> was the probability of “Male”.</p>
</div>
</div>
<div id="section-predictions-by-hand" class="section level2">
<h2>Predictions by hand</h2>
<p>Now that we know what <span class="math inline">\(p\)</span> is the probability <em>of</em>, we can use our model to make predictions.</p>
<p>Let’s say we want to estimate the Sex of a bonobo with a <code>fWHR</code> of 1.5.</p>
<p>According to our model, <span class="math inline">\(logit(\hat{p}) = \hat{\beta_0} + \hat{\beta_1}x\)</span> so <span class="math inline">\(logit(\hat{p})\)</span> is</p>
<pre class="r"><code>b0 &lt;- as.numeric(round(coef(bonobo_logit)[1], digits = 3))
b1 &lt;- as.numeric(round(coef(bonobo_logit)[2], digits = 3))
b0 + b1 * 1.5</code></pre>
<pre><code>## [1] -0.314</code></pre>
<p>But it would probably make more sense to compute <span class="math inline">\(\hat{p} = \frac{e^{-4.388 + 2.716 x_i}}{(1 + e^{-4.388 + 2.716 x_i})}\)</span>:</p>
<pre class="r"><code>p_hat &lt;- exp(b0 + b1 * 1.5) / (1 + exp(b0 + b1 * 1.5))
p_hat</code></pre>
<pre><code>## [1] 0.4221387</code></pre>
<p>So according to our model, the probability of a bonobo with <code>fWHR</code> 1.5 being Male is about 0.42. (If we had to guess its sex, I guess we’d guess Female - but reporting the probability actually gives a bit more information.)</p>
<p>We can also automate these calculations in R. The function <code>predict()</code> can return either the log-odds (<span class="math inline">\(logit(p)\)</span>) or the probability; we get the first by asking for a prediction of <code>type = 'link'</code> and the probability by asking for a prediction of <code>type = 'response'</code>.</p>
<pre class="r"><code>new_data &lt;- data.frame(fWHR = 1.5)
predict(bonobo_logit, newdata = new_data, type = &#39;link&#39;)</code></pre>
<pre><code>##          1 
## -0.3143138</code></pre>
<pre class="r"><code>predict(bonobo_logit, newdata = new_data, type = &#39;response&#39;)</code></pre>
<pre><code>##         1 
## 0.4220621</code></pre>
</div>
<div id="section-prediction-plots-by-hand" class="section level2">
<h2>Prediction plots by Hand</h2>
<p>Finally, we can plot the fitted model. We’ll overlay the observed data-points, too, coding them as 0 for “Female” and 1 for “Male”.</p>
<pre class="r"><code>bonobos &lt;- bonobos %&gt;%
  mutate(iSex = ifelse(Sex == &quot;Male&quot;, 1, 0))
new_data &lt;- data.frame(fWHR = seq(from = 1, by = 0.01, to = 2))
new_data &lt;- new_data %&gt;%
  mutate(preds = predict(bonobo_logit, newdata = new_data, type = &#39;response&#39;))
gf_line(preds ~ fWHR, data = new_data) %&gt;%
  gf_point(iSex ~ fWHR, data = bonobos, alpha = 0.3)</code></pre>
<p><img src="LogisticRegression_files/figure-html/unnamed-chunk-7-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>From this exploration of the predictions, it’s pretty clear that our model is not great at predicting sex from fWHR. Could we measure how well it’s doing, or test whether fWHR is a “good” predictor? We can consider using ANOVA for this.</p>
</div>
<div id="section-prediction-plots-in-r" class="section level2">
<h2>Prediction plots in R</h2>
<p>All the ways that we have made predictions so far have been kind of a LOT of R code and a lot of work for us. Can we hand all that work over to R and get a pretty picture out? YES!</p>
<p>In other words, we want a simpler way to create <em>prediction plots</em> showing model values. Ideally, we want a graph that <strong>includes uncertainty</strong> (that is, confidence intervals on the predicted values). And one that will work if and when we include <em>more</em> than just a single predictor variable. We can use the <code>ggeffects::ggpredict()</code> function to do ALL this, just like we did for linear regression models fitted with <code>lm()</code>.</p>
<pre class="r"><code>library(ggeffects)
ggpredict(bonobo_logit, 
          terms = c(&quot;fWHR&quot;)) |&gt;
  plot()</code></pre>
<pre><code>## Data were &#39;prettified&#39;. Consider using `terms=&quot;fWHR [all]&quot;` to get smooth plots.</code></pre>
<p><img src="LogisticRegression_files/figure-html/unnamed-chunk-8-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>The only downside there is the y axis label: It’s labelled “Probability of Sex” but which sex? Edit below to improve the label:</p>
<div class="tutorial-exercise" data-label="relabel-y" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>library(ggeffects)
ggpredict(bonobo_logit, 
          terms = c(&quot;fWHR&quot;)) |&gt;
  plot()</code></pre>
<script type="application/json" data-ui-opts="1">{"engine":"r","has_checker":false,"caption":"<span data-i18n=\"text.enginecap\" data-i18n-opts=\"{&quot;engine&quot;:&quot;R&quot;}\">R Code<\/span>"}</script>
</div>
<div class="tutorial-exercise-support" data-label="relabel-y-hint-1" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>library(ggeffects)
ggpredict(bonobo_logit, 
          terms = c(&quot;fWHR&quot;)) |&gt;
  plot() |&gt;
  gf_labs(y = ...)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="relabel-y-hint-2" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>library(ggeffects)
ggpredict(bonobo_logit, 
          terms = c(&quot;fWHR&quot;)) |&gt;
  plot() |&gt;
  gf_labs(y = &quot;Predicted probability of being male&quot;)</code></pre>
</div>
<p>The code above will work for any model; you just need to customize the inputs: the name of <em>your</em> fitted model instead of <code>bonobo_logit</code>; the name of <em>your</em> predictor(s) of interest instead of “fWHR”; and an axis label that makes sense for <em>your</em> model.</p>
</div>
<div id="section-how-the-magic-happens-mle" class="section level2">
<h2>How the Magic Happens: MLE</h2>
<p>But how did R obtain the model parameter estimates for us?</p>
<p><strong>Maximum likelihood estimation!</strong></p>
<p>We can do it ourselves, too. First, we need to write down an expression for the likelihood of our model.</p>
<p>Let’s begin with the fact that the likelihood of observing a “success” is <span class="math inline">\(\pi(\mathbf{x})\)</span>, while the likelihood of observing a “failure” is <span class="math inline">\((1-\pi(\mathbf{x}))\)</span> (so <span class="math inline">\(\pi\)</span> is the probability of success, which depends on the predictor values <span class="math inline">\(\mathbf{x}\)</span>). We’ll also assume the response variable is recoded as an indicator variable, with value 0 for failures and 1 for successes. Then we have the likelihood</p>
<p><span class="math display">\[\mathcal{L(\mathbf{\beta}; \mathbf{x})} = \prod_{i = 1}^{n} \pi(x_i)^{y_i} (1 - \pi(x_i))^{(1 - y_i)}\]</span></p>
<p>In other words, the likelihood is a product with one term per observation; <span class="math inline">\(\pi(x_i)\)</span> for successes, and <span class="math inline">\((1 - \pi(x_i))\)</span> for failures.</p>
<p>Taking the log-likelihood, we get</p>
<p><span class="math display">\[log(\mathcal{L}(\mathbf{\beta}; \mathbf{x})) = \ell(\mathbf{\beta}; \mathbf{x}) = \sum_{i=1}^{n} y_i log(\pi(x_i)) + (1 - y_i)log(1 - \pi(x_i)) \]</span></p>
<p>Grouping together the terms with <span class="math inline">\(y_i\)</span>,</p>
<p><span class="math display">\[\ell(\mathbf{\beta}; \mathbf{x}) = \sum_{i=1}^{n} log(1 - \pi(x_i)) + y_i log \bigg{(} \frac{\pi(x_i)}{(1 - \pi(x_i))} \bigg{)}\]</span> Since <span class="math inline">\(log \bigg{(} \frac{\pi(x_i)}{(1 - \pi(x_i))} \bigg{)} = \beta_0 + \beta_1x_i\)</span>, we could make a substitution in the second term of the sum, if we wanted.</p>
<p>We can also make a little more progress analytically, but will eventually find that there is not a closed-form solution for <span class="math inline">\(\mathbf{\beta}\)</span> in terms of the data.</p>
<div id="section-numerical-mle" class="section level3">
<h3>Numerical MLE</h3>
<p>In this case, our only workable solution is to optimize the likelihood numerically.</p>
<p>As a preliminary, we have to create an indicator-variable version of the response variable. Its value will be 0 for “failures” and 1 for “successes” (here, “Male” bonobos).</p>
<pre class="r"><code>bonobos &lt;- bonobos %&gt;%
  mutate(iSex = ifelse(Sex == &quot;Male&quot;, 1, 0))</code></pre>
<p>First, we need to write an R function to compute the log-likelihood. We can use our somewhat-simplified expression if we want, but actually all we need is the fact that the likelihood is a product with one term for each observation: <span class="math inline">\(\pi(x_i)\)</span> for successes and <span class="math inline">\((1 - \pi(x_i))\)</span> for failures. In addition, we need to know how <span class="math inline">\(\pi\)</span> (the probability of success) depends on the predictor variable value and the slope and intercept estimates. Remember, <span class="math inline">\(\pi(\mathbf{x})\)</span> is a length-n vector that depends on <span class="math inline">\(\mathbf{x}\)</span> and <span class="math inline">\(\mathbf{\beta}\)</span>; <span class="math inline">\(\mathbf{\pi}\)</span> is <em>not</em> itself a parameter of the model.</p>
<pre class="r"><code>logit_ll &lt;- function(beta, bonobos){
  # beta[1] = intercept and beta[2] = slope.
  pi &lt;- exp(beta[1] + beta[2]*bonobos$fWHR) / 
    (1 + exp(beta[1] + beta[2]*bonobos$fWHR))
  sum(dbinom(bonobos$iSex, 1, pi, log = TRUE))
}

maxLik(logit_ll, start = c(-2, 4), bonobos = bonobos)</code></pre>
<pre><code>## Maximum Likelihood estimation
## Newton-Raphson maximisation, 9 iterations
## Return code 1: gradient close to zero (gradtol)
## Log-Likelihood: -43.79198 (2 free parameter(s))
## Estimate(s): -4.388338 2.716016</code></pre>
<p>Success! (These values are the same as the ones we got from <code>glm()</code>).</p>
<pre class="r"><code>summary(bonobo_logit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Sex ~ fWHR, family = binomial(link = &quot;logit&quot;), 
##     data = bonobos)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5427  -0.9531  -0.8238   1.2331   1.8658  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)   -4.388      2.138  -2.053   0.0401 *
## fWHR           2.716      1.448   1.876   0.0607 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 91.365  on 67  degrees of freedom
## Residual deviance: 87.584  on 66  degrees of freedom
## AIC: 91.584
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div id="section-other-links" class="section level3">
<h3>Other links?</h3>
<p>Think about what would change in the code above, if we wanted to fit a <em>probit</em> or <em>c-log-log</em> model instead. The only thing that changes in those models is the <em>transformation</em> we use on the probability <span class="math inline">\(\pi(x_i)\)</span> – in other words, with a different link function, the calculation of <span class="math inline">\(\pi\)</span> would change, but the <code>sum(dbinom(...))</code> part would <em>not</em>!</p>
</div>
</div>
<div id="section-odds-again" class="section level2">
<h2>Odds, again</h2>
<p>Don’t you just love thinking about odds ratios? Aren’t they just the most intuitive thing?</p>
<p>What, no? Really, you don’t think so?</p>
<p>Maybe you should work with them for 10-20 more years, and <em>then</em> maybe you will start to think of them as the best way to communicate information about relative probabilities?</p>
<p>OK, sorry for the sarcasm. The fact is, many people find odds ratios un-intuitive to work with and think about. My honest recommendation is that, if you are going to work with models like these in an applied setting, the best way to communicate the results is to compute and report (and probably summarize graphically) <em>predicted probabilities</em> according to the fitted model.</p>
<p>We saw earlier how to make these prediction plots using <code>ggeffects::ggpredict() |&gt; plot()</code>.</p>
<p>However, there <em>is</em> a (somewhat) useful way to interpret the parameters of a logistic regression model in terms of odds ratios. It’s kind of analogous to interpreting a slope of a linear regression, along the lines of, “if the predictor value increases by 1, then the response increases by [slope].”</p>
<p>Obviously, the way we have used the logit link and the Binomial distribution means that same interpretation won’t hold for logistic regression slopes. But…</p>
<p>We know that</p>
<p><span class="math display">\[ log(\text{odds}) = \beta_0 + \beta_1x\]</span></p>
<p>So it follows that</p>
<p><span class="math display">\[ \text{odds} = e^{\beta_0 + \beta_1 x} = e^{\beta_0} (e^{\beta_1})^{x}\]</span></p>
<p>In other words, every time that <span class="math inline">\(x\)</span> increases by 1 unit, the <em>odds of success</em> are <em>multiplied</em> by a factor of <span class="math inline">\(e^{\beta_1}\)</span>.</p>
</div>
<div id="section-some-inference-for-logistic-regression" class="section level2">
<h2>(Some) Inference for Logistic Regression</h2>
<p>While we do not have an analytical derivation of an estimator for the standard error of the slope (or intercept) estimates in terms of the data, we do know a few things:</p>
<ul>
<li>R reports estimated standard errors in its <code>glm()</code> model summary. These are obtained from the variance-covariance matrix (<code>vcov()</code>) for the parameter estimates (which is estimated during the log-likelihood maximization procedure - we have not dug deep into the details.) Running <code>sqrt(diag(vcov(fitted_model)))</code> in R extracts these standard error estimates.</li>
</ul>
<pre class="r"><code>summary(bonobo_logit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Sex ~ fWHR, family = binomial(link = &quot;logit&quot;), 
##     data = bonobos)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5427  -0.9531  -0.8238   1.2331   1.8658  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)   -4.388      2.138  -2.053   0.0401 *
## fWHR           2.716      1.448   1.876   0.0607 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 91.365  on 67  degrees of freedom
## Residual deviance: 87.584  on 66  degrees of freedom
## AIC: 91.584
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>sqrt(diag(vcov(bonobo_logit)))</code></pre>
<pre><code>## (Intercept)        fWHR 
##    2.137884    1.447898</code></pre>
<ul>
<li>Since the binomial distribution has only one parameter, and no second “dispersion” parameter needs to be estimated in order to estimate the variance, we can use a standard normal distribution to get the <span class="math inline">\(z^*\)</span> multipliers and p-values we need to compute CIs and carry out tests for the model parameters (i.e., we can do Wald tests using the SEs from the model output). For the slope in our bonobo model:</li>
</ul>
<pre class="r"><code>slope_Wald_CI &lt;- coef(bonobo_logit)[2] + 
  c(-1,1) * qnorm(0.975) * sqrt(diag(vcov(bonobo_logit)))[2]
slope_Wald_CI</code></pre>
<pre><code>## [1] -0.1218125  5.5538452</code></pre>
<ul>
<li><p>As for <code>lm()</code>, the summary already contains p-values for tests of the null hypotheses that the slope or intercept are zero.</p></li>
<li><p>To get a CI for odds-ratio multiplier <span class="math inline">\(e^{\beta_1}\)</span>, we just exponetiate the upper and lower bounds of the CI for <span class="math inline">\(\beta_1\)</span>. Notice that on this scale the CI won’t be symmetric about the estimate <span class="math inline">\(e^\beta_1\)</span>.</p></li>
</ul>
<pre class="r"><code>slope_Wald_OR_CI &lt;- exp(slope_Wald_CI)
slope_Wald_OR_CI</code></pre>
<pre><code>## [1]   0.8853144 258.2285859</code></pre>
<ul>
<li>We can also ask R to compute the confidence intervals for us. In this case, it will use likelihood profiling (like the likelihood-ratio-test-based CIs we used in Chapter 5), yielding similar but slightly different results to the Wald CIs above.</li>
</ul>
<pre class="r"><code>confint(bonobo_logit)</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                  2.5 %     97.5 %
## (Intercept) -8.8535762 -0.3569309
## fWHR        -0.0211761  5.7418731</code></pre>
<pre class="r"><code>exp(confint(bonobo_logit))</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                    2.5 %      97.5 %
## (Intercept) 0.0001428699   0.6998208
## fWHR        0.9790465376 311.6476164</code></pre>
<p>All right, so we see that the slope of our model is <em>not 0</em>, but our CI is quite wide, indicating quite a lot of uncertainty in our estimate.</p>
<p>We probably want to ask a lot more questions about “goodness” of predictors and goodness of fit! (And perhaps consider multiple predictors, too.) We’ll return to this idea in the last week of class.</p>
</div>
<div id="section-more" class="section level2">
<h2>More</h2>
<p>If you would like an alternative intro to logistic regression that takes a different approach than FAStR, check out:</p>
<p><a href="https://data.princeton.edu/wws509/notes/c3.pdf" class="uri">https://data.princeton.edu/wws509/notes/c3.pdf</a></p>
(this is optional extra reference material). 
<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
# library(checkr)
# library(statPREP)
library(tibble)
library(ggformula)
library(mosaic)
#library(fastR)
#library(fastR2)
library(maxLik)
theme_set(theme_bw(base_size=16))
# knitr::opts_chunk$set(exercise.checker = checkr::checkr_tutor)
knitr::opts_chunk$set(
  echo = TRUE,
  fig.align = "center",
  fig.width = 6, fig.height = 2.5)
tutorial_options(exercise.eval = FALSE)

set.seed(14)
bonobos <- read.csv('http://sldr.netlify.com/data/bonobo_faces.csv') %>%
  mutate(Sex = factor(Sex)) %>%
  na.omit() 
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::prepare_tutorial_state(session)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::i18n_observe_tutorial_language(input, session)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::event_trigger(session, "session_stop")
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-relabel-y-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-relabel-y-code-editor`)), session)
output$`tutorial-exercise-relabel-y-output` <- renderUI({
  `tutorial-exercise-relabel-y-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_cache(structure(list(global_setup = structure(c("library(learnr)", 
"# library(checkr)", "# library(statPREP)", "library(tibble)", 
"library(ggformula)", "library(mosaic)", "#library(fastR)", "#library(fastR2)", 
"library(maxLik)", "theme_set(theme_bw(base_size=16))", "# knitr::opts_chunk$set(exercise.checker = checkr::checkr_tutor)", 
"knitr::opts_chunk$set(", "  echo = TRUE,", "  fig.align = \"center\",", 
"  fig.width = 6, fig.height = 2.5)", "tutorial_options(exercise.eval = FALSE)", 
"", "set.seed(14)", "bonobos <- read.csv('http://sldr.netlify.com/data/bonobo_faces.csv') %>%", 
"  mutate(Sex = factor(Sex)) %>%", "  na.omit() "), chunk_opts = list(
    label = "setup", include = FALSE)), setup = NULL, chunks = list(
    list(label = "relabel-y", code = "library(ggeffects)\nggpredict(bonobo_logit, \n          terms = c(\"fWHR\")) |>\n  plot()", 
        opts = list(label = "\"relabel-y\"", exercise = "TRUE"), 
        engine = "r")), code_check = NULL, error_check = NULL, 
    check = NULL, solution = NULL, test_cases = NULL, options = list(
        eval = FALSE, echo = TRUE, results = "markup", tidy = FALSE, 
        tidy.opts = NULL, collapse = FALSE, prompt = FALSE, comment = NA, 
        highlight = FALSE, size = "normalsize", background = "#F7F7F7", 
        strip.white = TRUE, cache = 0, cache.path = "LogisticRegression_cache/html/", 
        cache.vars = NULL, cache.lazy = TRUE, dependson = NULL, 
        autodep = FALSE, cache.rebuild = FALSE, fig.keep = "high", 
        fig.show = "asis", fig.align = "center", fig.path = "LogisticRegression_files/figure-html/", 
        dev = "png", dev.args = NULL, dpi = 192, fig.ext = "png", 
        fig.width = 6, fig.height = 2.5, fig.env = "figure", 
        fig.cap = NULL, fig.scap = NULL, fig.lp = "fig:", fig.subcap = NULL, 
        fig.pos = "", out.width = 576, out.height = NULL, out.extra = NULL, 
        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, 
        aniopts = "controls,loop", warning = TRUE, error = FALSE, 
        message = TRUE, render = NULL, ref.label = NULL, child = NULL, 
        engine = "r", split = FALSE, include = TRUE, purl = TRUE, 
        max.print = 1000, exercise.eval = FALSE, label = "relabel-y", 
        exercise = TRUE, code = c("library(ggeffects)", "ggpredict(bonobo_logit, ", 
        "          terms = c(\"fWHR\")) |>", "  plot()"), out.width.px = 576, 
        out.height.px = 240, params.src = " relabel-y, exercise = TRUE", 
        fig.num = 0, exercise.df_print = "paged", exercise.checker = "NULL"), 
    engine = "r"), class = "tutorial_exercise"))
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["header-attrs"]},{"type":"character","attributes":{},"value":["2.13"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pandoc"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["header-attrs.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1.9019"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["i18n"]},{"type":"character","attributes":{},"value":["1.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/i18n"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["i18next.min.js","tutorial-i18n-init.js"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["<script id=\"i18n-cstm-trns\" type=\"application/json\">{\"language\":\"en\",\"resources\":{\"en\":{\"translation\":{\"button\":{\"runcode\":\"Run Code\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Hint\",\"hint_plural\":\"Hints\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Next Hint\",\"hintprev\":\"Previous Hint\",\"solution\":\"Solution\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copy to Clipboard\",\"startover\":\"Start Over\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continue\",\"submitanswer\":\"Submit Answer\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Previous Topic\",\"nexttopic\":\"Next Topic\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Try Again\"},\"text\":{\"startover\":\"Start Over\",\"areyousure\":\"Are you sure you want to start over? (all exercise progress will be reset)\",\"youmustcomplete\":\"You must complete the\",\"exercise\":\"exercise\",\"exercise_plural\":\"exercises\",\"inthissection\":\"in this section before continuing.\",\"code\":\"Code\",\"enginecap\":\"{{engine}} $t(text.code)\",\"quiz\":\"Quiz\",\"blank\":\"blank\",\"blank_plural\":\"blanks\",\"exercisecontainsblank\":\"This exercise contains {{count}} $t(text.blank).\",\"pleasereplaceblank\":\"Please replace {{blank}} with valid code.\",\"unparsable\":\"It looks like this might not be valid R code. R cannot determine how to turn your text into a complete command. You may have forgotten to fill in a blank, to remove an underscore, to include a comma between arguments, or to close an opening <code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code> or <code>{<\\/code> with a matching <code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code> or <code>}<\\/code>.\\n\",\"unparsablequotes\":\"<p>It looks like your R code contains specially formatted quotation marks or &quot;curly&quot; quotes (<code>{{character}}<\\/code>) around character strings, making your code invalid. R requires character values to be contained in straight quotation marks (<code>&quot;<\\/code> or <code>'<\\/code>).<\\/p> {{code}} <p>Don't worry, this is a common source of errors when you copy code from another app that applies its own formatting to text. You can try replacing the code on that line with the following. There may be other places that need to be fixed, too.<\\/p> {{suggestion}}\\n\",\"unparsableunicode\":\"<p>It looks like your R code contains an unexpected special character (<code>{{character}}<\\/code>) that makes your code invalid.<\\/p> {{code}} <p>Sometimes your code may contain a special character that looks like a regular character, especially if you copy and paste the code from another app. Try deleting the special character from your code and retyping it manually.<\\/p>\\n\",\"unparsableunicodesuggestion\":\"<p>It looks like your R code contains an unexpected special character (<code>{{character}}<\\/code>) that makes your code invalid.<\\/p> {{code}} <p>Sometimes your code may contain a special character that looks like a regular character, especially if you copy and paste the code from another app. You can try replacing the code on that line with the following. There may be other places that need to be fixed, too.<\\/p> {{suggestion}}\\n\",\"and\":\"and\",\"or\":\"or\",\"listcomma\":\", \",\"oxfordcomma\":\",\"}}},\"fr\":{\"translation\":{\"button\":{\"runcode\":\"Lancer le Code\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Indication\",\"hint_plural\":\"Indications\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Indication Suivante\",\"hintprev\":\"Indication Précédente\",\"solution\":\"Solution\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copier dans le Presse-papier\",\"startover\":\"Recommencer\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuer\",\"submitanswer\":\"Soumettre\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Chapitre Précédent\",\"nexttopic\":\"Chapitre Suivant\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Réessayer\"},\"text\":{\"startover\":\"Recommencer\",\"areyousure\":\"Êtes-vous certains de vouloir recommencer? (La progression sera remise à zéro)\",\"youmustcomplete\":\"Vous devez d'abord compléter\",\"exercise\":\"l'exercice\",\"exercise_plural\":\"des exercices\",\"inthissection\":\"de cette section avec de continuer.\",\"code\":\"Code\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\",\"and\":\"et\",\"or\":\"ou\",\"oxfordcomma\":\"\"}}},\"es\":{\"translation\":{\"button\":{\"runcode\":\"Ejecutar código\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Pista\",\"hint_plural\":\"Pistas\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Siguiente pista\",\"hintprev\":\"Pista anterior\",\"solution\":\"Solución\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copiar al portapapeles\",\"startover\":\"Reiniciar\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuar\",\"submitanswer\":\"Enviar respuesta\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Tema anterior\",\"nexttopic\":\"Tema siguiente\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Volver a intentar\"},\"text\":{\"startover\":\"Reiniciar\",\"areyousure\":\"¿De verdad quieres empezar de nuevo? (todo el progreso del ejercicio se perderá)\",\"youmustcomplete\":\"Debes completar\",\"exercise\":\"el ejercicio\",\"exercise_plural\":\"los ejercicios\",\"inthissection\":\"en esta sección antes de continuar.\",\"code\":\"Código\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Cuestionario\",\"and\":\"y\",\"or\":\"o\",\"oxfordcomma\":\"\"}}},\"pt\":{\"translation\":{\"button\":{\"runcode\":\"Executar código\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Dica\",\"hint_plural\":\"Dicas\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Próxima dica\",\"hintprev\":\"Dica anterior\",\"solution\":\"Solução\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copiar para a área de transferência\",\"startover\":\"Reiniciar\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuar\",\"submitanswer\":\"Enviar resposta\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Tópico anterior\",\"nexttopic\":\"Próximo tópico\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Tentar novamente\"},\"text\":{\"startover\":\"Reiniciar\",\"areyousure\":\"Tem certeza que deseja começar novamente? (todo o progresso feito será perdido)\",\"youmustcomplete\":\"Você deve completar\",\"exercise\":\"o exercício\",\"exercise_plural\":\"os exercícios\",\"inthissection\":\"nesta seção antes de continuar.\",\"code\":\"Código\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\",\"and\":\"e\",\"or\":\"ou\",\"oxfordcomma\":\"\"}}},\"tr\":{\"translation\":{\"button\":{\"runcode\":\"Çalıştırma Kodu\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Ipucu\",\"hint_plural\":\"İpuçları\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Sonraki İpucu\",\"hintprev\":\"Önceki İpucu\",\"solution\":\"Çözüm\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Pano'ya Kopyala\",\"startover\":\"Baştan Başlamak\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Devam et\",\"submitanswer\":\"Cevabı onayla\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Önceki Konu\",\"nexttopic\":\"Sonraki Konu\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Tekrar Deneyin\"},\"text\":{\"startover\":\"Baştan Başlamak\",\"areyousure\":\"Baştan başlamak istediğinizden emin misiniz? (tüm egzersiz ilerlemesi kaybolacak)\",\"youmustcomplete\":\"Tamamlamalısın\",\"exercise\":\"egzersiz\",\"exercise_plural\":\"egzersizler\",\"inthissection\":\"devam etmeden önce bu bölümde\",\"code\":\"Kod\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Sınav\",\"oxfordcomma\":\"\"}}},\"emo\":{\"translation\":{\"button\":{\"runcode\":\"🏃\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"💡\",\"hint_plural\":\"$t(button.hint)\",\"hinttitle\":\"$t(button.hint)\",\"solution\":\"🎯\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"📋\",\"startover\":\"⏮\",\"startovertitle\":\"Start Over\",\"continue\":\"✅\",\"submitanswer\":\"🆗\",\"submitanswertitle\":\"Submit Answer\",\"previoustopic\":\"⬅\",\"nexttopic\":\"➡\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"🔁\"},\"text\":{\"startover\":\"⏮\",\"areyousure\":\"🤔\",\"youmustcomplete\":\"⚠️ 👉 🧑‍💻\",\"exercise\":\"\",\"exercise_plural\":\"\",\"inthissection\":\"\",\"code\":\"💻\",\"enginecap\":\"$t(text.code) {{engine}}\",\"oxfordcomma\":\"\"}}},\"eu\":{\"translation\":{\"button\":{\"runcode\":\"Kodea egikaritu\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Laguntza\",\"hint_plural\":\"Laguntza\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Aurreko laguntza\",\"hintprev\":\"Hurrengo laguntza\",\"solution\":\"Ebazpena\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Arbelean kopiatu\",\"startover\":\"Berrabiarazi\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Jarraitu\",\"submitanswer\":\"Erantzuna bidali\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Aurreko atala\",\"nexttopic\":\"Hurrengo atala\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Berriro saiatu\"},\"text\":{\"startover\":\"Berrabiarazi\",\"areyousure\":\"Berriro hasi nahi duzu? (egindako lana galdu egingo da)\",\"youmustcomplete\":\"Aurrera egin baino lehen atal honetako\",\"exercise\":\"ariketa egin behar duzu.\",\"exercise_plural\":\"ariketak egin behar dituzu.\",\"inthissection\":\"\",\"code\":\"Kodea\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Galdetegia\",\"oxfordcomma\":\"\"}}},\"de\":{\"translation\":{\"button\":{\"runcode\":\"Code ausführen\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Tipp\",\"hint_plural\":\"Tipps\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Nächster Tipp\",\"hintprev\":\"Vorheriger Tipp\",\"solution\":\"Lösung\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"In die Zwischenablage kopieren\",\"startover\":\"Neustart\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Weiter\",\"submitanswer\":\"Antwort einreichen\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Vorheriges Kapitel\",\"nexttopic\":\"Nächstes Kapitel\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Nochmal versuchen\"},\"text\":{\"startover\":\"Neustart\",\"areyousure\":\"Bist du sicher, dass du neustarten willst? (der gesamte Lernfortschritt wird gelöscht)\",\"youmustcomplete\":\"Vervollstädinge\",\"exercise\":\"die Übung\",\"exercise_plural\":\"die Übungen\",\"inthissection\":\"in diesem Kapitel, bevor du fortfährst.\",\"code\":\"Code\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\",\"blank\":\"Lücke\",\"blank_plural\":\"Lücken\",\"pleasereplaceblank\":\"Bitte ersetze {{blank}} mit gültigem Code.\",\"unparsable\":\"Dies scheint kein gültiger R Code zu sein. R kann deinen Text nicht in einen gültigen Befehl übersetzen. Du hast vielleicht vergessen, die Lücke zu füllen, einen Unterstrich zu entfernen, ein Komma zwischen Argumente zu setzen oder ein eröffnendes <code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code> oder <code>{<\\/code> mit einem zugehörigen <code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code> oder <code>}<\\/code> zu schließen.\\n\",\"and\":\"und\",\"or\":\"oder\",\"listcomma\":\", \",\"oxfordcomma\":\",\"}}},\"ko\":{\"translation\":{\"button\":{\"runcode\":\"코드 실행\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"힌트\",\"hint_plural\":\"힌트들\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"다음 힌트\",\"hintprev\":\"이전 힌트\",\"solution\":\"솔루션\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"클립보드에 복사\",\"startover\":\"재학습\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"다음 학습으로\",\"submitanswer\":\"정답 제출\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"이전 토픽\",\"nexttopic\":\"다음 토픽\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"재시도\"},\"text\":{\"startover\":\"재학습\",\"areyousure\":\"다시 시작 하시겠습니까? (모든 예제의 진행 정보가 재설정됩니다)\",\"youmustcomplete\":\"당신은 완료해야 합니다\",\"exercise\":\"연습문제\",\"exercise_plural\":\"연습문제들\",\"inthissection\":\"이 섹션을 실행하기 전에\",\"code\":\"코드\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"퀴즈\",\"blank\":\"공백\",\"blank_plural\":\"공백들\",\"exercisecontainsblank\":\"이 연습문제에는 {{count}}개의 $t(text.blank)이 포함되어 있습니다.\",\"pleasereplaceblank\":\"{{blank}}를 유효한 코드로 바꾸십시오.\",\"unparsable\":\"이것은 유효한 R 코드가 아닐 수 있습니다. R은 텍스트를 완전한 명령으로 변환하는 방법을 결정할 수 없습니다. 당신은 공백이나 밑줄을 대체하여 채우기, 인수를 컴마로 구분하기, 또는 <code>&quot;<\\/code>, <code>'<\\/code>, <code>(<\\/code> , <code>{<\\/code>로 시작하는 구문을 닫는 <code>&quot;<\\/code>, <code>'<\\/code>, <code>)<\\/code>, <code>}<\\/code>을 잊었을 수도 있습니다.\\n\",\"and\":\"그리고\",\"or\":\"혹은\",\"listcomma\":\", \",\"oxfordcomma\":\"\"}}}}}<\/script>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1.9019"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1.9019"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9019"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","broom","bslib","checkmate","cli","colorspace","compiler","crayon","crosstalk","curl","datasets","DBI","digest","dplyr","ellipsis","evaluate","fansi","farver","fastmap","forcats","generics","ggdendro","ggeffects","ggforce","ggformula","ggplot2","ggrepel","ggridges","ggstance","glue","graphics","grDevices","grid","gridExtra","gtable","haven","highr","hms","htmltools","htmlwidgets","httpuv","insight","jquerylib","jsonlite","knitr","labeling","labelled","later","lattice","leaflet","learnr","lifecycle","magrittr","markdown","MASS","Matrix","maxLik","methods","mime","miscTools","mosaic","mosaicCore","mosaicData","munsell","pillar","pkgconfig","plyr","polyclip","promises","purrr","R6","Rcpp","readr","rlang","rmarkdown","rprojroot","rstudioapi","sandwich","sass","scales","shiny","sjlabelled","snakecase","splines","stats","stringi","stringr","tibble","tidyr","tidyselect","tools","tweenr","tzdb","utf8","utils","vctrs","withr","xfun","xtable","yaml","zoo"]},{"type":"character","attributes":{},"value":["0.2.1","1.4.1","4.1.2","0.7.12","0.3.1","2.0.0","3.2.0","2.0-3","4.1.2","1.5.1","1.2.0","4.3.2","4.1.2","1.1.2","0.6.29","1.0.8","0.3.2","0.15","1.0.3","2.1.0","1.1.0","0.5.1","0.1.2","0.1.23","1.1.2","0.3.3","0.10.1","3.3.5","0.9.1","0.5.3","0.3.5","1.6.2","4.1.2","4.1.2","4.1.2","2.3","0.3.0","2.4.3","0.9","1.1.1","0.5.2","1.5.4","1.6.5","0.17.0","0.1.4","1.8.0","1.38","0.4.2","2.9.0","1.3.0","0.20-45","2.1.1","0.10.1.9019","1.0.1","2.0.3","1.1","7.3-56","1.4-1","1.5-2","4.1.2","0.12","0.6-26","1.8.3","0.9.0","0.20.2","0.5.0","1.7.0","2.0.3","1.8.7","1.10-0","1.2.0.1","0.3.4","2.5.1","1.0.8.3","2.1.2","1.0.2","2.13","2.0.3","0.13","3.0-1","0.4.1","1.1.1","1.7.1","1.2.0","0.11.0","4.1.2","4.1.2","1.7.6","1.4.0","3.1.6","1.2.0","1.1.2","4.1.2","1.0.2","0.3.0","1.2.2","4.1.2","0.4.0","2.5.0","0.30","1.8-4","2.3.5","1.8-9"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Logistic Regression (and Friends)</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->



<!-- Build Tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
